import type { Metadata } from "next";
import "./globals.css";
import { AlertProvider } from "@/components/shared/AlertProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full">
        <AlertProvider>{children}</AlertProvider>
      </body>
    </html>
  );
}
